/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coding

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertNull

class MainTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = Main()
        assertNull(null, "assert null should work")
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
